// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpTKW074mzPMUoL12XQBMebRuURpJL3I',
    appId: '1:259293067866:web:c684aa3ca89f81adf83663',
    messagingSenderId: '259293067866',
    projectId: 'test-firebase-88560',
    authDomain: 'test-firebase-88560.firebaseapp.com',
    storageBucket: 'test-firebase-88560.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlhnexSNpdl7xwYyprEA6nFi0UywkhjSo',
    appId: '1:259293067866:android:7e0869349d98c92ef83663',
    messagingSenderId: '259293067866',
    projectId: 'test-firebase-88560',
    storageBucket: 'test-firebase-88560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzaOz553vW6U-RP-Y7G5rck6hcvs5prA',
    appId: '1:259293067866:ios:3161f96e553e3303f83663',
    messagingSenderId: '259293067866',
    projectId: 'test-firebase-88560',
    storageBucket: 'test-firebase-88560.appspot.com',
    iosClientId: '259293067866-fa5epg5n083stabho1mjli4ohktp0dpo.apps.googleusercontent.com',
    iosBundleId: 'com.eitelleria.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzaOz553vW6U-RP-Y7G5rck6hcvs5prA',
    appId: '1:259293067866:ios:3161f96e553e3303f83663',
    messagingSenderId: '259293067866',
    projectId: 'test-firebase-88560',
    storageBucket: 'test-firebase-88560.appspot.com',
    iosClientId: '259293067866-fa5epg5n083stabho1mjli4ohktp0dpo.apps.googleusercontent.com',
    iosBundleId: 'com.eitelleria.testFirebase',
  );
}
